x-airflow-common: &airflow-common
  image: apache/airflow:2.7.3
  env_file:
    - .env
  environment:
    AIRFLOW__CORE__EXECUTOR: ${AIRFLOW__CORE__EXECUTOR}
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_POSTGRES_USER}:${AIRFLOW_POSTGRES_PASSWORD}@${AIRFLOW_POSTGRES_CONTAINER_NAME}/${AIRFLOW_POSTGRES_DB}
    AIRFLOW__CORE__DEFAULT_TIMEZONE: ${AIRFLOW__CORE__DEFAULT_TIMEZONE}
    AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW__CORE__FERNET_KEY}
    AIRFLOW__CORE__LOAD_EXAMPLES: ${AIRFLOW__CORE__LOAD_EXAMPLES}

    _PIP_ADDITIONAL_REQUIREMENTS: "requests pytz pymongo python-dotenv"

    PYTHONPATH: /opt/airflow/src

    DB_HOST: postgres-airflow
    DB_NAME: ${AIRFLOW_POSTGRES_DB}
    DB_USER: ${AIRFLOW_POSTGRES_USER}
    DB_PASSWORD: ${AIRFLOW_POSTGRES_PASSWORD}

  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/plugins:/opt/airflow/plugins
    - ./src:/opt/airflow/src

  user: "${AIRFLOW_UID}:0"

  depends_on:
    postgres-airflow:
      condition: service_healthy

services:

  # =========================
  # POSTGRES AIRFLOW
  # =========================
  postgres-airflow:
    image: postgres:13
    container_name: ${AIRFLOW_POSTGRES_CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${AIRFLOW_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AIRFLOW_POSTGRES_PASSWORD}
      POSTGRES_DB: ${AIRFLOW_POSTGRES_DB}
    volumes:
      - postgres-airflow-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${AIRFLOW_POSTGRES_USER}", "-d", "${AIRFLOW_POSTGRES_DB}"]
      interval: 5s
      retries: 5

  # =========================
  # AIRFLOW
  # =========================
  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    command: >
      bash -c "airflow db migrate && \
      airflow users create \
      --username ${AIRFLOW_ADMIN_USERNAME} \
      --password ${AIRFLOW_ADMIN_PASSWORD} \
      --firstname Admin \
      --lastname User \
      --role Admin
      --email ${AIRFLOW_ADMIN_EMAIL}"
    restart: "no"
    healthcheck:
      test: ["CMD-SHELL", "echo done"]
      interval: 5s
      retries: 1

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    command: webserver
    ports:
      - "8082:8080"
    depends_on:
      airflow-init:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    command: scheduler
    depends_on:
      airflow-init:
        condition: service_healthy

  # =========================
  # MONGODB
  # =========================
  mongo-datalake:
    image: mongo:8.0 
    container_name: ${MONGO_CONTAINER_NAME}
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    healthcheck:
      test: ["CMD-SHELL", "echo 'db.runCommand(\"ping\").ok' | mongosh localhost:27017/test --username $${MONGO_USER} --password $${MONGO_PASSWORD} --authenticationDatabase admin --quiet || exit 1"]
      interval: 5s
      retries: 5

  # =========================
  # POSTGRES ORGANIZED
  # =========================
  postgres-organized:
    image: postgres:13
    container_name: ${POSTGRES_CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-organized-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      retries: 5

  # # =========================
  # # LOKI
  # # =========================
  # loki:
  #   image: grafana/loki:2.9.3
  #   ports:
  #     - "3100:3100"
  #   command: -config.file=/etc/loki/local-config.yaml

  # # =========================
  # # PROMTAIL
  # # =========================
  # promtail:
  #   image: grafana/promtail:2.9.3
  #   volumes:
  #     - ./airflow/logs:/var/log/airflow
  #     - ./monitoring/promtail/promtail-config.yml:/etc/promtail/config.yml
  #   command: -config.file=/etc/promtail/config.yml
  #   depends_on:
  #     - loki

  # # =========================
  # # GRAFANA
  # # =========================
  # grafana:
  #   image: grafana/grafana:10.2.3
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - GF_SECURITY_ADMIN_USER=admin
  #     - GF_SECURITY_ADMIN_PASSWORD=admin
  #   volumes:
  #     - ./monitoring/grafana/data:/var/lib/grafana
  #   depends_on:
  #     - loki

volumes:
  postgres-airflow-data:
  mongo-data:
  mongo-config:
  postgres-organized-data: