x-airflow-common: &airflow-common
  image: apache/airflow:2.11.0
  env_file:
    - .env
  environment:
    AIRFLOW__CORE__EXECUTOR: ${AIRFLOW__CORE__EXECUTOR}
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_POSTGRES_USER}:${AIRFLOW_POSTGRES_PASSWORD}@${AIRFLOW_POSTGRES_CONTAINER_NAME}/${AIRFLOW_POSTGRES_DB}
    AIRFLOW__CORE__DEFAULT_TIMEZONE: ${AIRFLOW__CORE__DEFAULT_TIMEZONE}
    AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW__CORE__FERNET_KEY}
    AIRFLOW__CORE__LOAD_EXAMPLES: ${AIRFLOW__CORE__LOAD_EXAMPLES}
    _PIP_ADDITIONAL_REQUIREMENTS: > 
      requests
      pytz
      pymongo
      python-dotenv
    PYTHONPATH: /opt/airflow/src

  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/plugins:/opt/airflow/plugins
    - ./scripts/airflow:/opt/airflow/src
    - /var/run/docker.sock:/var/run/docker.sock

  user: "${AIRFLOW_UID}:0"

  depends_on:
    postgres-airflow:
      condition: service_healthy

services:

  # =========================
  # POSTGRES AIRFLOW
  # =========================
  postgres-airflow:
    image: postgres:13
    container_name: ${AIRFLOW_POSTGRES_CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${AIRFLOW_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AIRFLOW_POSTGRES_PASSWORD}
      POSTGRES_DB: ${AIRFLOW_POSTGRES_DB}
    ports:
      - "${AIRFLOW_POSTGRES_CONTAINER_PORT}:5432"
    volumes:
      - postgres-airflow-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${AIRFLOW_POSTGRES_USER}", "-d", "${AIRFLOW_POSTGRES_DB}"]
      interval: 5s
      retries: 5

  postgres-airflow-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres-airflow-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://${AIRFLOW_POSTGRES_USER}:${AIRFLOW_POSTGRES_PASSWORD}@${AIRFLOW_POSTGRES_CONTAINER_NAME}:5432/${AIRFLOW_POSTGRES_DB}?sslmode=disable"
    restart: unless-stopped
    depends_on:
      postgres-airflow:
        condition: service_healthy

  # =========================
  # AIRFLOW
  # =========================
  airflow-init:
    <<: *airflow-common
    container_name: ${AIRFLOW_INIT_CONTAINER_NAME}
    command: >
      bash -c "airflow db migrate && \
      airflow users create \
      --username ${AIRFLOW_ADMIN_USERNAME} \
      --password ${AIRFLOW_ADMIN_PASSWORD} \
      --firstname Admin \
      --lastname User \
      --role Admin
      --email ${AIRFLOW_ADMIN_EMAIL}"
    restart: "no"
    healthcheck:
      test: ["CMD-SHELL", "airflow db check"]
      interval: 10s
      timeout: 10s
      retries: 5

  airflow-webserver:
    <<: *airflow-common
    container_name: ${AIRFLOW_WEBSERVER_CONTAINER_NAME}
    command: webserver
    ports:
      - "${AIRFLOW_WEBSERVER_CONTAINER_PORT}:8080"
    depends_on:
      airflow-init:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5

  airflow-webserver-exporter:
    image: pbweb/airflow-prometheus-exporter
    container_name: airflow-webserver-exporter
    environment:
      AIRFLOW_PROMETHEUS_DATABASE_BACKEND: postgres
      AIRFLOW_PROMETHEUS_DATABASE_HOST: ${AIRFLOW_POSTGRES_CONTAINER_NAME}
      AIRFLOW_PROMETHEUS_DATABASE_PORT: 5432
      AIRFLOW_PROMETHEUS_DATABASE_USER: ${AIRFLOW_POSTGRES_USER}
      AIRFLOW_PROMETHEUS_DATABASE_PASSWORD: ${AIRFLOW_POSTGRES_PASSWORD}
      AIRFLOW_PROMETHEUS_DATABASE_NAME: ${AIRFLOW_POSTGRES_DB}
    restart: unless-stopped
    depends_on:
      postgres-airflow:
        condition: service_healthy

  airflow-scheduler:
    <<: *airflow-common
    container_name: ${AIRFLOW_SCHEDULER_CONTAINER_NAME}
    command: scheduler
    depends_on:
      airflow-init:
        condition: service_healthy

  # =========================
  # MONGODB
  # =========================
  mongo-datalake:
    image: mongo:8.0 
    container_name: ${MONGO_CONTAINER_NAME}
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "${MONGO_CONTAINER_PORT}:27017"
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    healthcheck:
      test: ["CMD-SHELL", "echo 'db.runCommand(\"ping\").ok' | mongosh localhost:27017/test --username $${MONGO_USER} --password $${MONGO_PASSWORD} --authenticationDatabase admin --quiet || exit 1"]
      interval: 5s
      retries: 5

  mongo-datalake-exporter:
    image: percona/mongodb_exporter:0.40
    container_name: mongo-datalake-exporter
    command:
      - "--mongodb.uri=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_CONTAINER_NAME}:27017/admin"
    restart: unless-stopped
    depends_on:
      mongo-datalake:
        condition: service_healthy

  # =========================
  # POSTGRES ORGANIZED
  # =========================
  postgres-organized:
    image: postgres:13
    container_name: ${POSTGRES_CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_CONTAINER_PORT}:5432"
    volumes:
      - ./scripts/postgres_organized:/docker-entrypoint-initdb.d:ro
      - postgres-organized-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      retries: 5

  postgres-organized-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres-organized-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_CONTAINER_NAME}:5432/${POSTGRES_DB}?sslmode=disable"
    restart: unless-stopped
    depends_on:
      postgres-organized:
        condition: service_healthy

  ########################
  # KAFKA (KRaft mode)
  ########################
  # kafka:
  #   image: confluentinc/cp-kafka:7.5.0
  #   container_name: kafka
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
  #     KAFKA_NODE_ID: 1
  #     KAFKA_PROCESS_ROLES: "broker,controller"

  #     KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
  #     KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"

  #     KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  #     KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"

  #     KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  ########################
  # SPARK MASTER
  ########################
  spark-master:
    image: apache/spark:4.0.1-python3
    container_name: ${SPARK_MASTER_CONTAINER_NAME}
    env_file:
      - .env
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.master.Master
    ports:
      - "${SPARK_MASTER_PROTOCOL_CONTAINER_PORT}:7077"
      - "${SPARK_MASTER_WEB_CONTAINER_PORT}:8080"
    volumes:
      - ./spark/jobs:/opt/spark/jobs
      - ./spark/drivers/postgresql-42.7.9.jar:/opt/spark/jars/postgresql.jar:ro
      - ./spark/logs:/opt/spark/logs
    restart: unless-stopped

  ########################
  # SPARK WORKER
  ########################
  spark-worker:
    image: apache/spark:4.0.1-python3
    container_name: ${SPARK_WORKER_CONTAINER_NAME}
    env_file:
      - .env
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.worker.Worker
      spark://${SPARK_MASTER_CONTAINER_NAME}:7077
    volumes:
      - ./spark/jobs:/opt/spark/jobs
      - ./spark/drivers/postgresql-42.7.9.jar:/opt/spark/jars/postgresql.jar:ro
    restart: unless-stopped
    depends_on:
      - spark-master

  ########################
  # LOCAL MONITORING
  ########################
  node-exporter:
    image: prom/node-exporter

  ########################
  # PROMETHEUS
  ########################
  prometheus:
    image: prom/prometheus:latest
    container_name: ${PROMETHEUS_CONTAINER_NAME}
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=7d"
    ports:
      - "${PROMETHEUS_CONTAINER_PORT}:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    restart: unless-stopped

  ########################
  # GRAFANA
  ########################
  grafana:
    image: grafana/grafana:10.2.3
    container_name: ${GRAFANA_CONTAINER_NAME}
    ports:
      - "${GRAFANA_CONTAINER_PORT}:3000"
    restart: unless-stopped

volumes:
  postgres-airflow-data:
  mongo-data:
  mongo-config:
  postgres-organized-data:
  prometheus-data: