apiVersion: 1

datasources:
  - name: sncf_organized_data
    type: postgres
    url: ${POSTGRES_CONTAINER_NAME}:5432
    database: ${POSTGRES_DB}
    user: grafana_user
    password: grafana_password_123
    isDefault: true
    jsonData:
      sslmode: "disable"