apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: ${PROMETHEUS_CONTAINER_NAME}:${PROMETHEUS_CONTAINER_PORT}
    isDefault: false
    editable: true
    jsonData:
      sslmode: "disable"
      schema: "public"
