{
 "title": "Airflow & DAGs",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Airflow up",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airflow_up{instance=\"airflow-webserver-exporter:9112\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active DAGs",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 7, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "airflow_dag_active{instance=\"airflow-webserver-exporter:9112\"}",
     "legendFormat": "{{dag}}"
    }
   ]
  },
  {
   "title": "Task Duration (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "airflow_dag_run_state{instance=\"airflow-webserver-exporter:9112\"}",
     "legendFormat": "{{state}}"
    }
   ]
  }
 ]
}