{
 "title": "PostgreSQL - Databases",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "pg_stat_database_numbackends{datname=~\"sncf_organized_data|airflow\"}",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Transactions / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{datname=~\"sncf_organized_data|airflow\"}[1m])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Database Size (GB)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=~\"sncf_organized_data|airflow\"} / 1024 / 1024 / 1024",
     "legendFormat": "{{datname}}"
    }
   ]
  }
 ]
}