{
 "title": "Arrivées Marseille Saint Charles",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Nombre d'arrivées retardées",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(train_id) FROM marseille_arrivals WHERE (arrival_is_late = true AND $__timeFilter(arrival_scheduled))"
    }
   ]
  },
  {
   "title": "Temps moyen de retard sur les arrivées",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  avg(arrival_actual - arrival_scheduled) AS \"Temps de retard moyen\"\r\nFROM\r\n  marseille_arrivals\r\nWHERE\r\n  arrival_is_late = true \r\n  AND $__timeFilter(arrival_scheduled)"
    }
   ]
  },
  {
   "title": "Nombre de départs retardés",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(train_id) FROM marseille_arrivals WHERE (departure_is_late = true AND $__timeFilter(departure_scheduled)) "
    }
   ]
  },
  {
   "title": "Temps moyen de retard sur les départs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  avg(departure_actual - departure_scheduled) AS \"Temps de retard moyen\"\r\nFROM\r\n  marseille_arrivals\r\nWHERE\r\n  departure_is_late = true \r\n  AND $__timeFilter(departure_scheduled)"
    }
   ]
  },
  {
   "title": "Nombre d'arrivées par type de trains",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT train_type, COUNT(train_id) FROM marseille_arrivals WHERE $__timeFilter(arrival_scheduled) GROUP BY train_type "
    }
   ]
  },
  {
   "title": "Nombre de départ par type de trains",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT train_type, COUNT(train_id) FROM marseille_arrivals WHERE $__timeFilter(departure_scheduled) GROUP BY train_type "
    }
   ]
  }
 ]
}